<a href="https://colab.research.google.com/github/bhawana-khajuria/Image-Classification-with-the-MNIST-Dataset/blob/main/MNISTDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Image Classification with the MNIST Dataset

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam

# Visualization tools
import torchvision
import torchvision.transforms.v2 as transforms
import torchvision.transforms.functional as F
import matplotlib.pyplot as plt

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.is_available()

False

## Training and Validation Data and Labels
1. x_train: Images used for training the neural network
2. y_train: Correct labels for the x_train images, used to evaluate the model's predictions during training
3. x_valid: Images set aside for validating the performance of the model after it has been trained
4. y_valid: Correct labels for the x_valid images, used to evaluate the model's predictions after it has been trained

### Loading the Data Into Memory (with TorchVision)

In [3]:
train_set = torchvision.datasets.MNIST("./data/", train=True, download=True)
valid_set = torchvision.datasets.MNIST("./data/", train=False, download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 20.2MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 603kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 5.68MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 4.91MB/s]


In [4]:
train_set

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data/
    Split: Train

In [5]:
valid_set

Dataset MNIST
    Number of datapoints: 10000
    Root location: ./data/
    Split: Test

 ## Exploring the MNIST Data

In [6]:
x_0, y_0 = train_set[0]

In [7]:
x_0

In [8]:
type(x_0)

PIL.Image.Image

In [9]:
y_0

5

In [10]:
type(y_0)

int

## **Tensors**

In [11]:
trans = transforms.Compose([transforms.ToTensor()])
x_0_tensor = trans(x_0)

/usr/local/lib/python3.11/dist-packages/torchvision/transforms/v2/_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(


In [12]:
x_0_tensor.dtype

torch.float32

In [13]:
x_0_tensor.min()

tensor(0.)

In [14]:

x_0_tensor.max()

tensor(1.)

In [15]:
x_0_tensor.size()

torch.Size([1, 28, 28])

In [16]:
x_0_tensor

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [17]:
x_0_tensor.device

device(type='cpu')

## **Transforms**

In [18]:
trans = transforms.Compose([transforms.ToTensor()])

In [19]:
train_set.transform = trans
valid_set.transform = trans

## **DataLoaders**

In [20]:
batch_size = 32

train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_set, batch_size=batch_size)

## **Creating the Model**

In [21]:
layers = []
layers

[]

## **Flattening the Image**

In [22]:
test_matrix = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
test_matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
nn.Flatten()(test_matrix)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
batch_test_matrix = test_matrix[None, :]
batch_test_matrix

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [25]:
nn.Flatten()(batch_test_matrix)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
nn.Flatten()(test_matrix[:, None])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
layers = [
    nn.Flatten()
]
layers

[Flatten(start_dim=1, end_dim=-1)]

## **The Input Layer**

In [28]:
input_size = 1 * 28 * 28

In [29]:
layers = [
    nn.Flatten(),
    nn.Linear(input_size, 512),  # Input
    nn.ReLU(),  # Activation for input
]
layers

[Flatten(start_dim=1, end_dim=-1),
 Linear(in_features=784, out_features=512, bias=True),
 ReLU()]

## **The Hidden Layer**

In [30]:
layers = [
    nn.Flatten(),
    nn.Linear(input_size, 512),  # Input
    nn.ReLU(),  # Activation for input
    nn.Linear(512, 512),  # Hidden
    nn.ReLU()  # Activation for hidden
]
layers

[Flatten(start_dim=1, end_dim=-1),
 Linear(in_features=784, out_features=512, bias=True),
 ReLU(),
 Linear(in_features=512, out_features=512, bias=True),
 ReLU()]

## **The Output Layer**

In [31]:
n_classes = 10

layers = [
    nn.Flatten(),
    nn.Linear(input_size, 512),  # Input
    nn.ReLU(),  # Activation for input
    nn.Linear(512, 512),  # Hidden
    nn.ReLU(),  # Activation for hidden
    nn.Linear(512, n_classes)  # Output
]
layers

[Flatten(start_dim=1, end_dim=-1),
 Linear(in_features=784, out_features=512, bias=True),
 ReLU(),
 Linear(in_features=512, out_features=512, bias=True),
 ReLU(),
 Linear(in_features=512, out_features=10, bias=True)]

## **Compiling the Model**

In [32]:
model = nn.Sequential(*layers)
model

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=512, bias=True)
  (2): ReLU()
  (3): Linear(in_features=512, out_features=512, bias=True)
  (4): ReLU()
  (5): Linear(in_features=512, out_features=10, bias=True)
)

In [33]:
model.to(device)

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=512, bias=True)
  (2): ReLU()
  (3): Linear(in_features=512, out_features=512, bias=True)
  (4): ReLU()
  (5): Linear(in_features=512, out_features=10, bias=True)
)

In [34]:
next(model.parameters()).device

device(type='cpu')

In [35]:
model = torch.compile(model)

## **Training the Model**
 Loss and Optimization

In [36]:
loss_function = nn.CrossEntropyLoss()

In [37]:
optimizer = Adam(model.parameters())

## **Calculating Accuracy**

In [38]:
train_N = len(train_loader.dataset)
valid_N = len(valid_loader.dataset)

In [39]:
def get_batch_accuracy(output, y, N):
    pred = output.argmax(dim=1, keepdim=True)
    correct = pred.eq(y.view_as(pred)).sum().item()
    return correct / N

## **The Train Function**

In [40]:
def train():
    loss = 0
    accuracy = 0

    model.train()
    for x, y in train_loader:
        x, y = x.to(device), y.to(device)
        output = model(x)
        optimizer.zero_grad()
        batch_loss = loss_function(output, y)
        batch_loss.backward()
        optimizer.step()

        loss += batch_loss.item()
        accuracy += get_batch_accuracy(output, y, train_N)
    print('Train - Loss: {:.4f} Accuracy: {:.4f}'.format(loss, accuracy))

## **The Validate Function**

In [41]:
def validate():
    loss = 0
    accuracy = 0

    model.eval()
    with torch.no_grad():
        for x, y in valid_loader:
            x, y = x.to(device), y.to(device)
            output = model(x)

            loss += loss_function(output, y).item()
            accuracy += get_batch_accuracy(output, y, valid_N)
    print('Valid - Loss: {:.4f} Accuracy: {:.4f}'.format(loss, accuracy))

## **The Training Loop**

In [42]:
epochs = 5

for epoch in range(epochs):
    print('Epoch: {}'.format(epoch))
    train()
    validate()

Epoch: 0


No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'


Train - Loss: 382.4660 Accuracy: 0.9374
Valid - Loss: 39.0943 Accuracy: 0.9619
Epoch: 1
Train - Loss: 158.7657 Accuracy: 0.9736
Valid - Loss: 24.9050 Accuracy: 0.9748
Epoch: 2
Train - Loss: 108.0548 Accuracy: 0.9820
Valid - Loss: 27.5611 Accuracy: 0.9749
Epoch: 3
Train - Loss: 84.5905 Accuracy: 0.9856
Valid - Loss: 23.2948 Accuracy: 0.9774
Epoch: 4
Train - Loss: 64.4318 Accuracy: 0.9886
Valid - Loss: 33.8840 Accuracy: 0.9720


In [44]:
import torch

# Example: Get a single batch from your DataLoader
x_0, y_0 = next(iter(valid_loader))  # or train_loader

# Move the input to the same device as the model
x_0_gpu = x_0.to(device)

# Ensure model is in evaluation mode
model.eval()

# Predict without tracking gradients
with torch.no_grad():
    prediction = model(x_0_gpu)
    print(prediction)

tensor([[-1.6206e+01, -1.3217e+00, -6.0522e+00, -9.9033e+00, -8.8599e+00,
         -1.1401e+01, -2.1334e+01,  1.6092e+01, -7.0489e+00, -1.7038e+00],
        [-1.5740e+01, -1.6465e+00,  1.3277e+01, -9.9128e+00, -1.1478e+01,
         -9.6475e+00, -5.2566e+00, -6.9831e+00, -2.9122e+00, -1.9561e+01],
        [-1.3586e+01,  1.1119e+01, -3.0512e+00, -1.6206e+01, -4.3482e+00,
         -8.0730e+00, -5.1293e+00, -2.5928e+00, -5.5682e+00, -9.2868e+00],
        [ 9.0212e+00, -1.0204e+01, -5.7612e+00, -1.3103e+01, -4.1977e+00,
         -6.2799e+00, -3.0779e+00, -7.5861e+00, -5.0003e+00, -2.2419e+00],
        [-8.5186e+00, -6.6493e+00, -1.4649e+00, -1.3358e+01,  8.8424e+00,
         -8.3190e+00, -1.1406e+01, -2.4052e+00, -9.7118e+00,  4.8232e-04],
        [-1.4718e+01,  1.2391e+01, -6.8045e+00, -1.9281e+01, -3.3975e+00,
         -1.2269e+01, -9.0837e+00, -2.9588e+00, -6.0227e+00, -9.4018e+00],
        [-1.5992e+01, -6.1610e+00, -9.7591e+00, -1.7228e+01,  1.2783e+01,
         -1.1551e+01, -1.2354e+0

In [45]:
prediction.argmax(dim=1, keepdim=True)

tensor([[7],
        [2],
        [1],
        [0],
        [4],
        [1],
        [4],
        [9],
        [5],
        [9],
        [0],
        [6],
        [9],
        [0],
        [1],
        [5],
        [9],
        [7],
        [3],
        [4],
        [9],
        [6],
        [6],
        [5],
        [4],
        [0],
        [7],
        [4],
        [0],
        [1],
        [3],
        [1]])

In [46]:
y_0

tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5,
        4, 0, 7, 4, 0, 1, 3, 1])